---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-discounts-helm
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  source:
    repoURL: https://github.com/davidseve/argocd-example-application.git
    targetRevision: HEAD
    path: ./argocd/applicationSet
  project: default
