apiVersion: v1
kind: Service
metadata:
  name: discounts
  labels:
    deployment: discounts
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    deployment: discounts
  type: ClusterIP
