apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: discounts
  labels:
    deployment: discounts
  annotations:
    argocd.argoproj.io/sync-wave: "50"    
spec:
  gateways:
  - mesh
  hosts:
  - discounts-istio-system.apps.{{ .Values.domain }}
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: discounts
        subset: stable
      weight: 100
    - destination:
        host: discounts
        subset: canary
      weight: 0
